language: python
python:
  - 2.7
install:
  - pip install --upgrade setuptools==12.0.5
  - python bootstrap.py --setuptools-version=12.0.5 -v 2.3.1
  - bin/buildout -N -q -t 3
script:
  - bin/py.test
before_script:
  - psql -c 'create database testdb;' -U postgres
addons:
  postgresql: "9.3"
