language: python
python:
  - 2.7
install:
  - python bootstrap.py -v 2.2.5
  - bin/buildout -N -q -t 3
script:
  - bin/py.test
before_script:
  - psql -c 'create database testdb;' -U postgres
addons:
  postgresql: "9.3"
