language: python
python:
  - 2.7
install:
  - pip install -U -r requirements.txt
  - buildout -N -q -t 5
script:
  - bin/py.test
before_script:
  - psql -c 'create database test;' -U postgres
services:
  - postgresql
